import type {
  BootstrapData,
  DemoType,
  Exercise,
  Goal,
  RoutineDay,
  RoutineExercise,
  RoutineTemplate,
  Workout,
} from "@/lib/types";

type ExerciseSeed = [
  id: string,
  name: string,
  slug: string,
  primaryMuscle: string,
  secondaryMuscles: string[],
  equipment: string,
  demoType: DemoType,
  restSeconds: number,
  instructions: string[],
  tips: string[],
];

const exerciseSeeds: ExerciseSeed[] = [
  [
    "ex-squat",
    "Agachamento livre",
    "agachamento-livre",
    "Quadríceps",
    ["Glúteos", "Posterior", "Core"],
    "Barra",
    "squat",
    120,
    [
      "Apoie a barra sobre a parte alta das costas e firme o tronco.",
      "Desça com joelhos acompanhando a direção dos pés.",
      "Empurre o chão e volte sem perder a posição da coluna.",
    ],
    ["Mantenha o pé inteiro apoiado.", "Use uma amplitude que preserve controle e postura."],
  ],
  [
    "ex-bench",
    "Supino reto com barra",
    "supino-reto-barra",
    "Peitoral",
    ["Tríceps", "Ombros"],
    "Barra",
    "press",
    120,
    [
      "Fixe escápulas e pés antes de retirar a barra.",
      "Desça a barra com controle até a linha média do peito.",
      "Empurre para cima mantendo punhos alinhados.",
    ],
    ["Não solte os ombros do banco.", "Peça ajuda quando treinar perto da falha."],
  ],
  [
    "ex-row",
    "Remada curvada com barra",
    "remada-curvada-barra",
    "Costas",
    ["Bíceps", "Posterior", "Core"],
    "Barra",
    "pull",
    105,
    [
      "Incline o tronco com a coluna neutra e joelhos destravados.",
      "Puxe a barra em direção ao abdômen.",
      "Desça até estender os braços sem perder a posição.",
    ],
    ["Pense em levar os cotovelos para trás.", "Evite transformar a repetição em um balanço."],
  ],
  [
    "ex-ohp",
    "Desenvolvimento com halteres",
    "desenvolvimento-halteres",
    "Ombros",
    ["Tríceps"],
    "Halteres",
    "press",
    90,
    [
      "Comece com halteres na altura dos ombros.",
      "Empurre acima da cabeça sem arquear excessivamente a lombar.",
      "Retorne devagar até a posição inicial.",
    ],
    ["Contraia abdômen e glúteos.", "Pare antes de perder o alinhamento dos punhos."],
  ],
  [
    "ex-rdl",
    "Levantamento terra romeno",
    "terra-romeno",
    "Posterior",
    ["Glúteos", "Lombar"],
    "Barra",
    "hinge",
    120,
    [
      "Segure a barra próxima às coxas e destrave os joelhos.",
      "Leve o quadril para trás mantendo a barra perto das pernas.",
      "Volte estendendo o quadril, sem hiperestender a coluna.",
    ],
    ["Procure tensão no posterior, não a maior amplitude possível.", "Mantenha o pescoço neutro."],
  ],
  [
    "ex-pulldown",
    "Puxada alta",
    "puxada-alta",
    "Costas",
    ["Bíceps"],
    "Polia",
    "pull",
    90,
    [
      "Segure a barra um pouco além da largura dos ombros.",
      "Puxe em direção ao alto do peito, levando cotovelos para baixo.",
      "Retorne com controle até alongar as costas.",
    ],
    ["Evite jogar o tronco para trás.", "Inicie o movimento deprimindo as escápulas."],
  ],
  [
    "ex-lunge",
    "Afundo com halteres",
    "afundo-halteres",
    "Quadríceps",
    ["Glúteos", "Posterior"],
    "Halteres",
    "lunge",
    90,
    [
      "Dê um passo confortável e estabilize os pés.",
      "Desça o joelho de trás em direção ao chão.",
      "Suba pressionando o pé da frente.",
    ],
    ["Mantenha o joelho da frente alinhado ao pé.", "Comece sem carga se o equilíbrio limitar o movimento."],
  ],
  [
    "ex-curl",
    "Rosca direta",
    "rosca-direta",
    "Bíceps",
    ["Antebraços"],
    "Barra",
    "curl",
    75,
    [
      "Mantenha cotovelos próximos ao corpo.",
      "Flexione os braços sem deslocar os ombros à frente.",
      "Desça a barra devagar até quase estender os cotovelos.",
    ],
    ["Use uma carga que não exija balanço.", "Controle a descida por completo."],
  ],
  [
    "ex-triceps",
    "Tríceps na polia",
    "triceps-polia",
    "Tríceps",
    [],
    "Polia",
    "extension",
    75,
    [
      "Trave os cotovelos ao lado do tronco.",
      "Estenda os braços até contrair o tríceps.",
      "Retorne sem deixar os cotovelos avançarem.",
    ],
    ["Mantenha os ombros baixos.", "Não use o peso do corpo para empurrar."],
  ],
  [
    "ex-legpress",
    "Leg press 45°",
    "leg-press-45",
    "Quadríceps",
    ["Glúteos", "Posterior"],
    "Máquina",
    "squat",
    105,
    [
      "Posicione os pés na plataforma e apoie toda a lombar.",
      "Desça a plataforma até a amplitude controlada.",
      "Empurre sem travar os joelhos com impacto.",
    ],
    ["Não deixe o quadril enrolar no fim da descida.", "Mantenha joelhos acompanhando os pés."],
  ],
  [
    "ex-incline",
    "Supino inclinado com halteres",
    "supino-inclinado-halteres",
    "Peitoral",
    ["Ombros", "Tríceps"],
    "Halteres",
    "press",
    105,
    [
      "Ajuste o banco em uma inclinação moderada.",
      "Desça os halteres ao lado do peito com controle.",
      "Empurre para cima sem bater os halteres.",
    ],
    ["Mantenha escápulas apoiadas.", "Evite inclinação excessiva do banco."],
  ],
  [
    "ex-seatedrow",
    "Remada baixa",
    "remada-baixa",
    "Costas",
    ["Bíceps"],
    "Polia",
    "pull",
    90,
    [
      "Sente com tronco firme e braços estendidos.",
      "Puxe o cabo até o abdômen, aproximando as escápulas.",
      "Retorne sem arredondar a coluna.",
    ],
    ["Não transforme o movimento em extensão de tronco.", "Segure um instante na contração."],
  ],
  [
    "ex-lateral",
    "Elevação lateral",
    "elevacao-lateral",
    "Ombros",
    [],
    "Halteres",
    "raise",
    60,
    [
      "Segure os halteres ao lado do corpo com cotovelos destravados.",
      "Eleve os braços até perto da linha dos ombros.",
      "Desça devagar sem relaxar completamente.",
    ],
    ["Conduza o movimento pelos cotovelos.", "Evite encolher os ombros."],
  ],
  [
    "ex-plank",
    "Prancha",
    "prancha",
    "Core",
    ["Glúteos", "Ombros"],
    "Peso corporal",
    "core",
    60,
    [
      "Apoie antebraços e pontas dos pés.",
      "Alinhe cabeça, tronco e quadril.",
      "Respire mantendo abdômen e glúteos ativos.",
    ],
    ["Encerre a série quando perder a posição.", "Não prenda a respiração."],
  ],
  [
    "ex-crunch",
    "Abdominal na polia",
    "abdominal-polia",
    "Core",
    [],
    "Polia",
    "core",
    60,
    [
      "Ajoelhe-se segurando a corda junto à cabeça.",
      "Flexione o tronco aproximando costelas e pelve.",
      "Retorne controlando a carga, sem puxar com os braços.",
    ],
    ["Pense em enrolar o tronco.", "Mantenha o quadril relativamente estável."],
  ],
  [
    "ex-hipthrust",
    "Elevação pélvica",
    "elevacao-pelvica",
    "Glúteos",
    ["Posterior"],
    "Barra",
    "hinge",
    105,
    [
      "Apoie a parte alta das costas no banco e posicione a barra no quadril.",
      "Eleve o quadril até alinhar joelhos, quadril e ombros.",
      "Desça com controle sem perder a posição dos pés.",
    ],
    ["Finalize com glúteos, não com a lombar.", "Mantenha o queixo levemente recolhido."],
  ],
  [
    "ex-pullup",
    "Barra fixa",
    "barra-fixa",
    "Costas",
    ["Bíceps", "Core"],
    "Barra fixa",
    "pull",
    120,
    [
      "Comece pendurado com tronco firme.",
      "Puxe o peito em direção à barra conduzindo pelos cotovelos.",
      "Desça com controle até estender os braços.",
    ],
    ["Use assistência se necessário.", "Evite balanço para contar repetições."],
  ],
  [
    "ex-deadlift",
    "Levantamento terra",
    "levantamento-terra",
    "Posterior",
    ["Glúteos", "Costas", "Core"],
    "Barra",
    "hinge",
    150,
    [
      "Aproxime a barra das canelas e firme a pegada.",
      "Crie tensão no tronco antes de tirar a barra do chão.",
      "Estenda joelhos e quadril mantendo a barra próxima ao corpo.",
    ],
    ["Aprenda o padrão com carga leve.", "Não arredonde a lombar para buscar a barra."],
  ],
  [
    "ex-flys",
    "Crucifixo na máquina",
    "crucifixo-maquina",
    "Peitoral",
    ["Ombros"],
    "Máquina",
    "press",
    75,
    [
      "Ajuste o banco para alinhar as mãos ao peito.",
      "Aproxime os braços mantendo os cotovelos levemente flexionados.",
      "Retorne até alongar o peitoral sem forçar o ombro.",
    ],
    ["Mantenha costas apoiadas.", "Não deixe a carga bater entre repetições."],
  ],
  [
    "ex-hamcurl",
    "Mesa flexora",
    "mesa-flexora",
    "Posterior",
    [],
    "Máquina",
    "curl",
    75,
    [
      "Ajuste o rolo logo acima dos calcanhares.",
      "Flexione os joelhos mantendo o quadril apoiado.",
      "Retorne controlando a extensão.",
    ],
    ["Evite levantar o quadril.", "Use amplitude sem dor no joelho."],
  ],
  [
    "ex-legext",
    "Cadeira extensora",
    "cadeira-extensora",
    "Quadríceps",
    [],
    "Máquina",
    "extension",
    75,
    [
      "Alinhe o eixo da máquina ao joelho.",
      "Estenda as pernas sem dar impulso.",
      "Desça controlando até a posição inicial.",
    ],
    ["Ajuste o encosto para apoiar o quadril.", "Evite impacto no fim da extensão."],
  ],
  [
    "ex-calf",
    "Panturrilha em pé",
    "panturrilha-em-pe",
    "Panturrilhas",
    [],
    "Máquina",
    "extension",
    60,
    [
      "Apoie a parte da frente dos pés na plataforma.",
      "Eleve os calcanhares até contrair as panturrilhas.",
      "Desça devagar até sentir alongamento controlado.",
    ],
    ["Não quique no fundo.", "Use apoio para manter equilíbrio."],
  ],
  [
    "ex-facepull",
    "Face pull",
    "face-pull",
    "Ombros",
    ["Costas"],
    "Polia",
    "pull",
    60,
    [
      "Ajuste a corda na altura do rosto.",
      "Puxe separando as pontas e levando cotovelos para fora.",
      "Retorne sem perder a posição do tronco.",
    ],
    ["Use carga moderada.", "Termine com as mãos ao lado do rosto."],
  ],
  [
    "ex-goblet",
    "Agachamento goblet",
    "agachamento-goblet",
    "Quadríceps",
    ["Glúteos", "Core"],
    "Halter",
    "squat",
    90,
    [
      "Segure um halter junto ao peito.",
      "Agache mantendo o tronco firme e joelhos alinhados.",
      "Suba empurrando o chão com o pé inteiro.",
    ],
    ["É uma boa opção para aprender o agachamento.", "Não deixe o halter afastar do corpo."],
  ],
];

export const demoExercises: Exercise[] = exerciseSeeds.map(
  ([id, name, slug, primaryMuscle, secondaryMuscles, equipment, demoType, restSeconds, instructions, tips]) => ({
    id,
    name,
    slug,
    primaryMuscle,
    secondaryMuscles,
    equipment,
    demoType,
    restSeconds,
    instructions,
    tips,
    videoUrl: null,
    ownerId: null,
    isCustom: false,
  }),
);

let sequence = 0;

function routineExercise(
  exerciseId: string,
  sets: number,
  repsMin: number,
  repsMax: number,
  restSeconds: number,
  notes = "",
): RoutineExercise {
  sequence += 1;
  return {
    id: `re-${sequence}`,
    exerciseId,
    order: sequence,
    sets,
    repsMin,
    repsMax,
    restSeconds,
    notes,
  };
}

function day(id: string, name: string, order: number, exercises: RoutineExercise[]): RoutineDay {
  return { id, name, order, exercises: exercises.map((exercise, index) => ({ ...exercise, order: index + 1 })) };
}

const templateBase: RoutineTemplate = {
  id: "tpl-base-3",
  slug: "base-3x",
  name: "Base 3x",
  level: "iniciante",
  goal: "hipertrofia",
  daysPerWeek: 3,
  durationWeeks: 8,
  sessionMinutes: 50,
  description: "Treino de corpo inteiro, simples de seguir e fácil de progredir.",
  tags: ["Corpo inteiro", "Fundamentos", "Academia"],
  days: [
    day("tpl-base-a", "Treino A", 1, [
      routineExercise("ex-squat", 3, 6, 8, 120),
      routineExercise("ex-bench", 3, 6, 10, 120),
      routineExercise("ex-row", 3, 8, 10, 105),
      routineExercise("ex-ohp", 3, 8, 12, 90),
      routineExercise("ex-plank", 3, 30, 45, 60, "Repetições representam segundos"),
    ]),
    day("tpl-base-b", "Treino B", 2, [
      routineExercise("ex-rdl", 3, 8, 10, 120),
      routineExercise("ex-pulldown", 3, 8, 12, 90),
      routineExercise("ex-lunge", 3, 8, 10, 90, "Repetições por perna"),
      routineExercise("ex-curl", 2, 10, 12, 75),
      routineExercise("ex-triceps", 2, 10, 12, 75),
    ]),
    day("tpl-base-c", "Treino C", 3, [
      routineExercise("ex-legpress", 3, 10, 12, 105),
      routineExercise("ex-incline", 3, 8, 12, 105),
      routineExercise("ex-seatedrow", 3, 8, 12, 90),
      routineExercise("ex-lateral", 3, 12, 15, 60),
      routineExercise("ex-crunch", 3, 12, 15, 60),
    ]),
  ],
};

const templateUpperLower: RoutineTemplate = {
  id: "tpl-upper-lower",
  slug: "superior-inferior-4x",
  name: "Superior / Inferior",
  level: "intermediario",
  goal: "hipertrofia",
  daysPerWeek: 4,
  durationWeeks: 10,
  sessionMinutes: 60,
  description: "Mais volume por grupo muscular sem transformar cada treino em uma maratona.",
  tags: ["4 dias", "Hipertrofia", "Progressão"],
  days: [
    day("tpl-ul-upper-a", "Superior A", 1, [
      routineExercise("ex-bench", 4, 5, 8, 120),
      routineExercise("ex-row", 4, 6, 10, 105),
      routineExercise("ex-ohp", 3, 8, 10, 90),
      routineExercise("ex-pulldown", 3, 8, 12, 90),
      routineExercise("ex-triceps", 3, 10, 14, 75),
      routineExercise("ex-curl", 3, 10, 14, 75),
    ]),
    day("tpl-ul-lower-a", "Inferior A", 2, [
      routineExercise("ex-squat", 4, 5, 8, 135),
      routineExercise("ex-rdl", 3, 8, 10, 120),
      routineExercise("ex-legpress", 3, 10, 12, 105),
      routineExercise("ex-hamcurl", 3, 10, 14, 75),
      routineExercise("ex-calf", 4, 10, 15, 60),
    ]),
    day("tpl-ul-upper-b", "Superior B", 3, [
      routineExercise("ex-incline", 4, 8, 10, 105),
      routineExercise("ex-pullup", 4, 6, 10, 120),
      routineExercise("ex-seatedrow", 3, 10, 12, 90),
      routineExercise("ex-lateral", 4, 12, 16, 60),
      routineExercise("ex-facepull", 3, 12, 15, 60),
      routineExercise("ex-curl", 3, 10, 12, 75),
    ]),
    day("tpl-ul-lower-b", "Inferior B", 4, [
      routineExercise("ex-deadlift", 3, 3, 5, 150),
      routineExercise("ex-lunge", 3, 8, 10, 90),
      routineExercise("ex-hipthrust", 4, 8, 12, 105),
      routineExercise("ex-legext", 3, 12, 15, 75),
      routineExercise("ex-crunch", 3, 12, 18, 60),
    ]),
  ],
};

const templatePpl: RoutineTemplate = {
  id: "tpl-ppl-5",
  slug: "push-pull-legs-5x",
  name: "Push / Pull / Legs",
  level: "intermediario",
  goal: "forca",
  daysPerWeek: 5,
  durationWeeks: 8,
  sessionMinutes: 65,
  description: "Divisão de cinco dias com compostos fortes e acessórios objetivos.",
  tags: ["5 dias", "Força", "Volume alto"],
  days: [
    day("tpl-ppl-push-a", "Push A", 1, [
      routineExercise("ex-bench", 4, 4, 6, 135),
      routineExercise("ex-ohp", 3, 6, 8, 105),
      routineExercise("ex-incline", 3, 8, 10, 90),
      routineExercise("ex-lateral", 4, 12, 16, 60),
      routineExercise("ex-triceps", 3, 10, 14, 75),
    ]),
    day("tpl-ppl-pull-a", "Pull A", 2, [
      routineExercise("ex-row", 4, 5, 8, 120),
      routineExercise("ex-pullup", 4, 6, 10, 120),
      routineExercise("ex-seatedrow", 3, 8, 12, 90),
      routineExercise("ex-facepull", 3, 12, 15, 60),
      routineExercise("ex-curl", 3, 8, 12, 75),
    ]),
    day("tpl-ppl-legs-a", "Legs A", 3, [
      routineExercise("ex-squat", 4, 4, 6, 150),
      routineExercise("ex-rdl", 4, 6, 10, 120),
      routineExercise("ex-legpress", 3, 10, 12, 105),
      routineExercise("ex-hamcurl", 3, 10, 14, 75),
      routineExercise("ex-calf", 4, 12, 16, 60),
    ]),
    day("tpl-ppl-push-b", "Push B", 4, [
      routineExercise("ex-incline", 4, 6, 10, 105),
      routineExercise("ex-ohp", 4, 6, 8, 105),
      routineExercise("ex-flys", 3, 12, 15, 75),
      routineExercise("ex-lateral", 4, 12, 18, 60),
      routineExercise("ex-triceps", 4, 10, 14, 75),
    ]),
    day("tpl-ppl-pull-b", "Pull B", 5, [
      routineExercise("ex-deadlift", 3, 3, 5, 150),
      routineExercise("ex-pulldown", 4, 8, 12, 90),
      routineExercise("ex-seatedrow", 4, 8, 12, 90),
      routineExercise("ex-facepull", 3, 12, 16, 60),
      routineExercise("ex-curl", 4, 10, 14, 75),
    ]),
  ],
};

export const demoTemplates: RoutineTemplate[] = [templateBase, templateUpperLower, templatePpl];

function createCompletedWorkout(index: number, date: string, goal: Goal = "hipertrofia"): Workout {
  const progressiveWeight = 48 + index * 2;
  return {
    id: `workout-history-${index}`,
    name: index % 3 === 0 ? "Treino A" : index % 3 === 1 ? "Treino B" : "Treino C",
    routineId: "demo-routine",
    routineDayId: templateBase.days[index % 3].id,
    startedAt: `${date}T18:10:00.000Z`,
    endedAt: `${date}T19:02:00.000Z`,
    durationSeconds: 3120 + index * 45,
    status: "completed",
    notes: goal === "forca" ? "Boa velocidade nas séries principais." : "Execução consistente.",
    exercises: [
      {
        id: `we-${index}-1`,
        exerciseId: "ex-bench",
        order: 1,
        restSeconds: 120,
        sets: [0, 1, 2].map((setIndex) => ({
          id: `ws-${index}-bench-${setIndex}`,
          setNumber: setIndex + 1,
          type: "normal",
          weight: progressiveWeight + setIndex * 2,
          reps: 10 - setIndex,
          rpe: 7 + setIndex * 0.5,
          completed: true,
          completedAt: `${date}T18:${20 + setIndex * 4}:00.000Z`,
        })),
      },
      {
        id: `we-${index}-2`,
        exerciseId: "ex-row",
        order: 2,
        restSeconds: 105,
        sets: [0, 1, 2].map((setIndex) => ({
          id: `ws-${index}-row-${setIndex}`,
          setNumber: setIndex + 1,
          type: "normal",
          weight: progressiveWeight - 4 + setIndex * 2,
          reps: 10,
          rpe: 7.5,
          completed: true,
          completedAt: `${date}T18:${38 + setIndex * 4}:00.000Z`,
        })),
      },
    ],
  };
}

const historyDates = [
  "2026-05-29",
  "2026-06-03",
  "2026-06-08",
  "2026-06-13",
  "2026-06-18",
  "2026-06-23",
  "2026-06-28",
  "2026-07-03",
  "2026-07-07",
];

export const demoWorkouts = historyDates.map((date, index) => createCompletedWorkout(index, date));

export function getDemoBootstrap(): BootstrapData {
  return {
    mode: "demo",
    user: {
      id: "demo-user",
      email: "demo@zym.app",
      name: "Daniel",
    },
    profile: {
      id: "demo-user",
      name: "Daniel",
      goal: "hipertrofia",
      level: "intermediario",
      daysPerWeek: 3,
      unit: "kg",
      defaultRestSeconds: 90,
      onboardingComplete: true,
    },
    exercises: demoExercises,
    templates: demoTemplates,
    routines: [],
    workouts: demoWorkouts,
    schedule: [
      { id: "schedule-1", date: "2026-07-10", routineDayId: "tpl-base-a", name: "Treino A", completed: false },
      { id: "schedule-2", date: "2026-07-12", routineDayId: "tpl-base-b", name: "Treino B", completed: false },
      { id: "schedule-3", date: "2026-07-14", routineDayId: "tpl-base-c", name: "Treino C", completed: false },
    ],
    activeWorkout: null,
  };
}
